---

# - name: "Install Python packages"
#   yum:
#     name: python2-psycopg2
#     state: present 

- name: stop fw
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  tags:
    - aboba

- name: aboba
  yum:
    name:  
      - https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      # - postgresql14-server
    state: present
  tags:
    - aboba

- name: aboba local
  yum:
    name:  
      #- https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      - postgresql14-server
    state: present
  tags:
    - aboba



- name: backu

  shell: "sudo su  - postgres -c 'PGPASSWORD=123 pg_basebackup -h 192.168.21.111 -U  repluser -p 5432 -D $PGDATA -Fp -Xs -P -R'"
  # shell: "PGPASSWORD='{{ db_password }}' pg_basebackup -h 192.168.21.111 -U  repluser -p 5432 -D $PGDATA -Fp -Xs -P -R"
  tags:
    - back


- name: restart postgresql-14
  systemd:
    name: postgresql-14
    state: restarted
    enabled: yes
  tags:
    - back


# - name: "Start and enable services"
#   service: "name={{ item }} state=restarted enabled=yes"
#   with_items:
#     - postgresql-14

# - name: promote
#   become_user: postgres
#   shell: "/usr/pgsql-14/bin/pg_ctl -D {{ pathtofiles }} promote"
#   # notify: restart postgres

  