---
# handlers file for rrobin
- name: restart postgresql-14
  systemd:
    name: postgresql-14
    state: restarted
    enabled: yes
    
- name: start postgresql-14
  systemd:
    name: postgresql-14
    state: started
    enabled: yes